
apiVersion: apps/v1
kind: Deployment
metadata:
 name: chaitudeploy
 namespace: test-ns
spec:
 replicas: 2
 selector:
   matchLabels:
    app: ram
 template: 
   metadata:
    labels:
     app: ram
   spec:
    containers:
    - name: chaitucon
      image: chaitu1812/chat
      ports:
       - containerPort: 8080
      resources:
       requests:
         cpu: "150m"
         memory: "120Mi"  
       limits:
         cpu: "300m"
         memory: "300Mi"    
---
apiVersion: v1
kind: Service
metadata:
 name: hpaservice
 namespace: test-ns
spec:
 type: NodePort
 selector:
  app: ram
 ports:
  - port: 80
    targetPort: 8080
    nodePort: 32246  
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
  namespace: test-ns  
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chaitudeploy
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20

