apiVersion: v1
kind: Pod
metadata:
  name: mc1
  labels: 
    multi: two  
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: 1st
    image: nginx
    ports:
     - containerPort: 80   
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  - name: 2nd
    image: debian
    volumeMounts:
    - name: html
      mountPath: /html
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          echo "hi chaitu"  >> /html/index.html;
         
          sleep 1;
        done
---
apiVersion: v1
kind: Service
metadata: 
 name: servicemulti
spec:
 type: NodePort
 selector:
   multi: two
 ports:
 - port: 8090
   targetPort: 80
     
