apiVersion: v1
kind: PersistentVolume
metadata:
 name: persistentvolume
 namespace: test-cs
spec:
 capacity:
  storage: 2Gi
 accessModes:
  - ReadWriteMany
 nfs: 
  server: 13.235.50.135
  path: /nfs/nfs_backup
