apiVersion: v1
kind: PersistentVolume
metadata:
 name: cs
spec:
 capacity:
  storage: 4Gi
 accessModes:
  - ReadWriteMany
 persistentVolumeReclaimPolicy: Retain   
 nfs:
  server: 172.31.33.68
  path: /nfs/nfs_tier
  readOnly: false
