apiVersion: v1
kind: Pod
metadata: 
 name: chat
 namespace: test-ns  
 labels: 
   name: chatlabel  
spec:  
 containers: 
 - name: chatcon
   image: chaitu1812/chat
   ports:
   - containerPort: 8080
 - name: nginx
   image: nginx
   ports:
   - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: chatsvc
 namespace: test-ns
spec:
  type: NodePort
  selector:  
    name: chatlabel
  ports:
   - port: 8081
     targetPort: 8080
     name: chat
   - port: 80
     targetPort: 80
     name: nginx    

