apiVersion: v1
kind: ReplicationController
metadata:
  name: chatrc
  namespace: test-ns
spec:
 replicas: 4
 template:
   metadata:
     name: chatpod
     labels: 
       app: chat
   spec:
     tolerations:
       - key: key
         operator: Exists
         effect: NoExecute  
     containers:
     - name: chatcon
       image: chaitu1812/chat
       ports:
       - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: chatservice
 namespace: test-ns
spec:
 type: NodePort
 selector:
  app: chat
 ports: 
  - port: 8081
    targetPort: 8080
    nodePort: 32256   

