apiVersion: v1
kind: ReplicationController
metadata:
  name: spring
  namespace: test-ns
spec:
 replicas: 2
 selector:
   app: spring
 template:
   metadata:
     name: spring
     labels: 
       app: spring
   spec:
     containers:
     - name: chatcon
       image: chaitu1812/springboot:v2.0
       ports:
       - containerPort: 8080
     nodeSelector:    
       chaitu: "geetha"

---
apiVersion: v1
kind: Service
metadata:
 name: springservice
 namespace: test-ns
spec:
 type: ClusterIP
 selector:
  app: spring
 ports: 
  - port: 8082
    targetPort: 8080
    

